### ISSUE TITLE
Laravel 5.4 Class 'PureIntellect\Tickets\TicketsServiceProvider' not found

### ISSUE THREAD

**Issue by agentelinux** [PureIntellect/Tickets#1]
Hi,

make sense?

$ php artisan vendor:publish --provider="PureIntellect\Tickets\TicketsServiceProvider"
PHP Fatal error:  Class 'PureIntellect\Tickets\TicketsServiceProvider' not found in /dev/apphosting/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 201                                                                  
  [Symfony\Component\Debug\Exception\FatalErrorException]         
  Class 'PureIntellect\Tickets\TicketsServiceProvider' not found

**Comment by brandenwagner** [comment]
Did you register the service provider in your config/app.php?

**Comment by brandenwagner** [comment]
I made some updates. see if these help. If not please feel free to re open the ticket.
